const test=require("node:test");
const assert=require("node:assert/strict");
const request=require("supertest");
const pino=require("pino");
const criarAplicacao=require("../src/app");
const {obterConfiguracao}=require("../src/shared/config/ambiente");
const {criarPool}=require("../src/shared/database/conexao");
const {criarEmailProviderFake}=require("../src/shared/providers/emailProvider");
const {criarHashDaSenha}=require("../src/modules/autenticacao/senha");
const {ESCOPO_LEITURA,ESCOPO_GESTAO}=require("../src/shared/providers/googleDriveProvider");
const criarChangesRepository=require("../src/modules/materiais/googleDriveChangesRepository");

const base=obterConfiguracao();
const configuracao=Object.assign({},base,{ambiente:"test",nivelDeLog:"silent",banco:Object.assign({},base.banco,{nome:process.env.DB_TEST_NAME||base.banco.nome+"_test"}),googleDrive:{clientId:"fase6.apps.googleusercontent.com",clientSecret:"segredo-fase6",pastaRaizId:"pastaRaizFaseSeis123",redirectUri:"http://localhost:3000/api/integracoes/google-drive/oauth/callback",refreshToken:"refresh-token-fase-seis",webhookUrl:"",intervaloChangesMs:60000,escopo:"https://www.googleapis.com/auth/drive"}});
configuracao.seguranca=Object.assign({},base.seguranca,{limiteAutenticacao:100,limiteUpload:100});
const pool=criarPool(configuracao.banco);
let sequencia=0;
const operacoes=[];
const itensDrive=new Map();
const provider={
  escopo:ESCOPO_GESTAO,pastaRaizId:configuracao.googleDrive.pastaRaizId,
  obterItem:async function obter(token,id){return itensDrive.get(id)||{id:id,name:"externo",mimeType:"application/vnd.google-apps.folder",parents:["foraDaRaiz"],trashed:false};},
  verificarDescendenteDaRaiz:async function verificar(token,item){if(!item||item.trashed)return false;let atual=item;for(let nivel=0;nivel<10;nivel+=1){if((atual.parents||[]).includes(configuracao.googleDrive.pastaRaizId))return true;atual=itensDrive.get((atual.parents||[])[0]);if(!atual)return false;}return false;},
  criarArquivo:async function criar(token,dados){sequencia+=1;operacoes.push(["criar",dados.pastaDriveId]);const item={id:"driveNovo"+sequencia,name:dados.nome,mimeType:dados.mimeType,size:String(dados.tamanho),parents:[dados.pastaDriveId],trashed:false};itensDrive.set(item.id,item);return item;},
  renomearArquivo:async function renomear(token,id,nome){operacoes.push(["renomear",id,nome]);const item=itensDrive.get(id);if(item)item.name=nome;return{id:id,name:nome};},
  moverArquivo:async function mover(token,id,origem,destino){operacoes.push(["mover",id,origem,destino]);const item=itensDrive.get(id);if(item)item.parents=[destino];return{id:id,parents:[destino]};},
  alterarLixeira:async function lixeira(token,id,estado){operacoes.push(["lixeira",id,estado]);const item=itensDrive.get(id);if(item)item.trashed=estado;return{id:id,trashed:estado};},
  excluirArquivo:async function excluir(token,id){operacoes.push(["excluir",id]);itensDrive.delete(id);return{};},
  gerarUrlAutorizacao:function gerar(){return"https://google.test";},trocarCodigoPorRefreshToken:async function trocar(){return"refresh-token-fase-seis";},listarArvore:async function listar(){return{raiz:{},pastas:[],arquivos:[]};}
};
const app=criarAplicacao(configuracao,pino({level:"silent"}),{pool:pool,emailProvider:criarEmailProviderFake(),googleDriveProvider:provider,agendarTarefaGoogleDrive:function ignorar(){},agendarTarefaGoogleDriveChanges:function ignorar(){}});
let usuarios;let pastaA;let pastaB;let pastaProibida;let materialId;

async function limparCategorias(){let removidas=1;while(removidas){const[r]=await pool.execute("DELETE c FROM categorias c LEFT JOIN categorias f ON f.categoria_pai_id=c.id WHERE f.id IS NULL");removidas=r.affectedRows;}}
async function limpar(){await pool.execute("DELETE FROM auditoria_materiais");await pool.execute("DELETE FROM notificacoes_google_drive");await pool.execute("DELETE FROM canais_google_drive");await pool.execute("DELETE FROM estado_changes_google_drive");await pool.execute("DELETE FROM materiais");await pool.execute("DELETE FROM auditoria_classificacao_categorias");await pool.execute("DELETE FROM permissoes_professor_categoria");await limparCategorias();await pool.execute("DELETE FROM disciplinas");await pool.execute("DELETE FROM concursos");await pool.execute("DELETE FROM credenciais_google_drive");await pool.execute("DELETE FROM estados_oauth_google_drive");await pool.execute("DELETE FROM sincronizacoes_google_drive");await pool.execute("DELETE FROM recuperacoes_senha");await pool.execute("DELETE FROM sessoes");await pool.execute("DELETE FROM usuarios");}
async function usuario(email,papel){const[r]=await pool.execute("INSERT INTO usuarios(email,senha_hash,papel)VALUES(?,?,?)",[email,await criarHashDaSenha("Senha-forte-fase-6"),papel]);return{id:Number(r.insertId),email:email,papel:papel};}
async function autenticar(papel){const agente=request.agent(app);const csrf=(await agente.get("/api/autenticacao/csrf")).body.csrfToken;assert.equal((await agente.post("/api/autenticacao/login").set("X-CSRF-Token",csrf).send({email:usuarios[papel].email,senha:"Senha-forte-fase-6"})).status,200);return{agente:agente,csrf:csrf};}

test.beforeEach(async function preparar(){await limpar();operacoes.length=0;itensDrive.clear();itensDrive.set(configuracao.googleDrive.pastaRaizId,{id:configuracao.googleDrive.pastaRaizId,mimeType:"application/vnd.google-apps.folder",parents:[],trashed:false});itensDrive.set("driveAreaA",{id:"driveAreaA",mimeType:"application/vnd.google-apps.folder",parents:[configuracao.googleDrive.pastaRaizId],trashed:false});itensDrive.set("driveAreaB",{id:"driveAreaB",mimeType:"application/vnd.google-apps.folder",parents:["driveAreaA"],trashed:false});itensDrive.set("driveProibida",{id:"driveProibida",mimeType:"application/vnd.google-apps.folder",parents:[configuracao.googleDrive.pastaRaizId],trashed:false});itensDrive.set("driveMaterial6",{id:"driveMaterial6",name:"original.pdf",mimeType:"application/pdf",parents:["driveAreaA"],trashed:false});usuarios={admin:await usuario("admin6@example.com","admin"),professor:await usuario("prof6@example.com","professor"),aluno:await usuario("aluno6@example.com","aluno")};const[a]=await pool.execute("INSERT INTO categorias(nome,drive_pasta_id)VALUES('Area A','driveAreaA')");pastaA=Number(a.insertId);const[b]=await pool.execute("INSERT INTO categorias(nome,categoria_pai_id,drive_pasta_id)VALUES('Subarea B',?,'driveAreaB')",[pastaA]);pastaB=Number(b.insertId);const[p]=await pool.execute("INSERT INTO categorias(nome,drive_pasta_id)VALUES('Proibida','driveProibida')");pastaProibida=Number(p.insertId);await pool.execute("INSERT INTO permissoes_professor_categoria(professor_id,categoria_id,concedida_por_usuario_id)VALUES(?,?,?)",[usuarios.professor.id,pastaA,usuarios.admin.id]);const[m]=await pool.execute("INSERT INTO materiais(drive_file_id,drive_parent_file_id,categoria_id,nome,mime_type,tipo,extensao,tamanho_bytes,disponivel,ultima_sincronizacao_drive_id)VALUES('driveMaterial6','driveAreaA',?,'original.pdf','application/pdf','pdf','pdf',20,1,NULL)",[pastaA]);materialId=Number(m.insertId);});
test.after(async function encerrar(){await limpar();await pool.end();});

test("upload valida PDF, video, CSRF, papeis, nomes, raiz e permissao por subarvore",async function(){const professor=await autenticar("professor");const pdf=Buffer.from("%PDF-1.7\nconteudo seguro","utf8");const ok=await professor.agente.post("/api/gestao-materiais").set("X-CSRF-Token",professor.csrf).field("categoriaId",String(pastaB)).attach("arquivo",pdf,{filename:"lista.pdf",contentType:"application/pdf"});assert.equal(ok.status,201);assert.equal(ok.body.nome,"lista.pdf");assert.equal(Object.prototype.hasOwnProperty.call(ok.body,"driveFileId"),false);assert.equal((await professor.agente.post("/api/gestao-materiais").field("categoriaId",String(pastaA)).attach("arquivo",pdf,{filename:"sem-csrf.pdf",contentType:"application/pdf"})).status,403);const proibido=await professor.agente.post("/api/gestao-materiais").set("X-CSRF-Token",professor.csrf).field("categoriaId",String(pastaProibida)).attach("arquivo",pdf,{filename:"lista.pdf",contentType:"application/pdf"});assert.equal(proibido.status,403);const falso=await professor.agente.post("/api/gestao-materiais").set("X-CSRF-Token",professor.csrf).field("categoriaId",String(pastaA)).attach("arquivo",Buffer.from("nao e pdf"),{filename:"falso.pdf",contentType:"application/pdf"});assert.equal(falso.status,400);const nomeInvalido=await professor.agente.post("/api/gestao-materiais").set("X-CSRF-Token",professor.csrf).field("categoriaId",String(pastaA)).field("nome","invalido/arquivo.pdf").attach("arquivo",pdf,{filename:"lista.pdf",contentType:"application/pdf"});assert.equal(nomeInvalido.status,400);const admin=await autenticar("admin");const video=Buffer.concat([Buffer.alloc(4),Buffer.from("ftyp"),Buffer.from("video seguro")]);const videoOk=await admin.agente.post("/api/gestao-materiais").set("X-CSRF-Token",admin.csrf).field("categoriaId",String(pastaProibida)).attach("arquivo",video,{filename:"aula.mp4",contentType:"video/mp4"});assert.equal(videoOk.status,201);assert.equal(videoOk.body.tipo,"video");const[fora]=await pool.execute("INSERT INTO categorias(nome,drive_pasta_id)VALUES('Fora da raiz','driveForaRaiz')");const foraRaiz=await admin.agente.post("/api/gestao-materiais").set("X-CSRF-Token",admin.csrf).field("categoriaId",String(fora.insertId)).attach("arquivo",pdf,{filename:"fora.pdf",contentType:"application/pdf"});assert.equal(foraRaiz.status,403);assert.equal(foraRaiz.body.erro.codigo,"PASTA_FORA_DA_RAIZ");const aluno=await autenticar("aluno");assert.equal((await aluno.agente.post("/api/gestao-materiais").set("X-CSRF-Token",aluno.csrf).field("categoriaId",String(pastaA)).attach("arquivo",pdf,{filename:"aluno.pdf",contentType:"application/pdf"})).status,403);});

test("edicao e movimento protegem mass assignment, concorrencia e IDOR",async function(){const professor=await autenticar("professor");const[disciplina]=await pool.execute("INSERT INTO disciplinas(nome)VALUES('Fisica Fase 6')");await pool.execute("UPDATE categorias SET disciplina_id=?,disciplina_estado='definida',disciplina_origem='manual' WHERE id=?",[disciplina.insertId,pastaB]);const[fora]=await pool.execute("INSERT INTO materiais(drive_file_id,drive_parent_file_id,categoria_id,nome,mime_type,tipo,extensao,disponivel,ultima_sincronizacao_drive_id)VALUES('driveFora6','driveProibida',?,'fora.pdf','application/pdf','pdf','pdf',1,NULL)",[pastaProibida]);assert.equal((await professor.agente.patch("/api/gestao-materiais/"+Number(fora.insertId)).set("X-CSRF-Token",professor.csrf).send({nome:"invasao.pdf",versao:1})).status,403);const editado=await professor.agente.patch("/api/gestao-materiais/"+materialId).set("X-CSRF-Token",professor.csrf).send({nome:"renomeado.pdf",versao:1});assert.equal(editado.status,200);assert.equal(editado.body.versao,2);const excesso=await professor.agente.patch("/api/gestao-materiais/"+materialId).set("X-CSRF-Token",professor.csrf).send({driveFileId:"forjado",versao:2});assert.equal(excesso.status,400);const destinoProibido=await professor.agente.patch("/api/gestao-materiais/"+materialId+"/mover").set("X-CSRF-Token",professor.csrf).send({categoriaId:pastaProibida,versao:2});assert.equal(destinoProibido.status,403);const movido=await professor.agente.patch("/api/gestao-materiais/"+materialId+"/mover").set("X-CSRF-Token",professor.csrf).send({categoriaId:pastaB,versao:2});assert.equal(movido.status,200);assert.equal(movido.body.categoriaId,pastaB);const aluno=await autenticar("aluno");const consulta=await aluno.agente.get("/api/acervo?busca=renomeado&disciplinaId="+disciplina.insertId);assert.equal(consulta.status,200);assert.equal(consulta.body.materiais[0].id,materialId);assert.match(consulta.body.materiais[0].caminho,/Subarea B/);const concorrente=await professor.agente.patch("/api/gestao-materiais/"+materialId).set("X-CSRF-Token",professor.csrf).send({nome:"atrasado.pdf",versao:2});assert.equal(concorrente.status,409);});

test("trava compartilhada impede operacao local durante sync ou Changes API",async function(){const professor=await autenticar("professor");const conexao=await pool.getConnection();try{const[trava]=await conexao.execute("SELECT GET_LOCK(LEFT(CONCAT('plantel_drive_operacao_',DATABASE()),64),0) AS adquirida");assert.equal(Number(trava[0].adquirida),1);const antes=operacoes.length;const resposta=await professor.agente.patch("/api/gestao-materiais/"+materialId).set("X-CSRF-Token",professor.csrf).send({nome:"nao-deve-chegar-ao-drive.pdf",versao:1});assert.equal(resposta.status,409);assert.equal(resposta.body.erro.codigo,"GOOGLE_DRIVE_OPERACAO_CONCORRENTE");assert.equal(operacoes.length,antes);}finally{await conexao.execute("SELECT RELEASE_LOCK(LEFT(CONCAT('plantel_drive_operacao_',DATABASE()),64))");conexao.release();}});

test("substituicao valida tipos, preserva materialId e lixeira bloqueia leitura",async function(){const professor=await autenticar("professor");const excesso=await professor.agente.post("/api/gestao-materiais/"+materialId+"/substituir").set("X-CSRF-Token",professor.csrf).field("versao","1").field("driveFileId","forjado").attach("arquivo",Buffer.from("%PDF-1.7\nnovo"),{filename:"novo.pdf",contentType:"application/pdf"});assert.equal(excesso.status,400);const proibido=await professor.agente.post("/api/gestao-materiais/"+materialId+"/substituir").set("X-CSRF-Token",professor.csrf).field("versao","1").attach("arquivo",Buffer.from([0x89,0x50,0x4e,0x47]),{filename:"imagem.png",contentType:"image/png"});assert.equal(proibido.status,400);const novo=await professor.agente.post("/api/gestao-materiais/"+materialId+"/substituir").set("X-CSRF-Token",professor.csrf).field("versao","1").attach("arquivo",Buffer.from("%PDF-1.7\nnovo"),{filename:"novo.pdf",contentType:"application/pdf"});assert.equal(novo.status,200);assert.equal(novo.body.id,materialId);const video=Buffer.concat([Buffer.alloc(4),Buffer.from("ftyp"),Buffer.from("substituto")]);const novoVideo=await professor.agente.post("/api/gestao-materiais/"+materialId+"/substituir").set("X-CSRF-Token",professor.csrf).field("versao","2").attach("arquivo",video,{filename:"novo.mp4",contentType:"video/mp4"});assert.equal(novoVideo.status,200);assert.equal(novoVideo.body.id,materialId);assert.equal(novoVideo.body.tipo,"video");const lixo=await professor.agente.post("/api/gestao-materiais/"+materialId+"/lixeira").set("X-CSRF-Token",professor.csrf).send({versao:3});assert.equal(lixo.status,200);const aluno=await autenticar("aluno");assert.equal((await aluno.agente.get("/api/acervo/materiais/"+materialId+"/download")).status,404);const consulta=await aluno.agente.get("/api/acervo?busca=original");assert.equal(consulta.body.paginacao.totalItens,0);});

test("somente admin restaura e exclui definitivamente arquivo temporario",async function(){const professor=await autenticar("professor");const[fora]=await pool.execute("INSERT INTO materiais(drive_file_id,drive_parent_file_id,categoria_id,nome,mime_type,tipo,extensao,disponivel,ultima_sincronizacao_drive_id)VALUES('driveLixoFora6','driveProibida',?,'fora-lixeira.pdf','application/pdf','pdf','pdf',1,NULL)",[pastaProibida]);assert.equal((await professor.agente.post("/api/gestao-materiais/"+Number(fora.insertId)+"/lixeira").set("X-CSRF-Token",professor.csrf).send({versao:1})).status,403);await professor.agente.post("/api/gestao-materiais/"+materialId+"/lixeira").set("X-CSRF-Token",professor.csrf).send({versao:1});assert.equal((await professor.agente.get("/api/gestao-materiais/lixeira")).status,403);const aluno=await autenticar("aluno");assert.equal((await aluno.agente.post("/api/gestao-materiais/"+materialId+"/lixeira").set("X-CSRF-Token",aluno.csrf).send({versao:2})).status,403);const admin=await autenticar("admin");const lista=await admin.agente.get("/api/gestao-materiais/lixeira");assert.equal(lista.status,200);assert.equal(lista.body[0].id,materialId);const restaurado=await admin.agente.post("/api/gestao-materiais/"+materialId+"/restaurar").set("X-CSRF-Token",admin.csrf).send({versao:2});assert.equal(restaurado.status,200);await admin.agente.post("/api/gestao-materiais/"+materialId+"/lixeira").set("X-CSRF-Token",admin.csrf).send({versao:3});const excluido=await admin.agente.delete("/api/gestao-materiais/"+materialId).set("X-CSRF-Token",admin.csrf).send({versao:4});assert.equal(excluido.status,200);const[estado]=await pool.execute("SELECT estado_gestao,disponivel FROM materiais WHERE id=?",[materialId]);assert.equal(estado[0].estado_gestao,"excluido");assert.equal(Number(estado[0].disponivel),0);});

test("escopo somente leitura exige reconexao antes de qualquer escrita",async function(){const professor=await autenticar("professor");provider.escopo=ESCOPO_LEITURA;try{const resposta=await professor.agente.post("/api/gestao-materiais").set("X-CSRF-Token",professor.csrf).field("categoriaId",String(pastaA)).attach("arquivo",Buffer.from("%PDF-1.7\nseguro"),{filename:"bloqueado.pdf",contentType:"application/pdf"});assert.equal(resposta.status,409);assert.equal(resposta.body.erro.codigo,"GOOGLE_RECONEXAO_ESCRITA_NECESSARIA");assert.equal(operacoes.length,0);}finally{provider.escopo=ESCOPO_GESTAO;}});

test("notificacao posterior permanece idempotente e nao retira material da lixeira",async function(){await pool.execute("UPDATE materiais SET estado_gestao='lixeira',disponivel=0,categoria_anterior_id=categoria_id WHERE id=?",[materialId]);const repository=criarChangesRepository(pool);const conexao=await pool.getConnection();try{await repository.aplicarAlteracoes(conexao,[{disponivel:true,item:{id:"driveMaterial6",parentId:"driveAreaA",name:"original.pdf",mimeType:"application/pdf",size:"20"}}],"pagina-depois-da-escrita");}finally{conexao.release();}const[estado]=await pool.execute("SELECT estado_gestao,disponivel FROM materiais WHERE id=?",[materialId]);assert.equal(estado[0].estado_gestao,"lixeira");assert.equal(Number(estado[0].disponivel),0);});
