CREATE TABLE avisos_biblioteca (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  texto VARCHAR(160) NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 0,
  ordem INT UNSIGNED NOT NULL DEFAULT 0,
  criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_avisos_ativos_ordem (ativo, ordem, id),
  CONSTRAINT chk_avisos_ativo CHECK (ativo IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
